### ISSUE TITLE
hello,

### ISSUE THREAD

**Issue by cachecleanerjeet** [ParveenBhadooOfficial/Jio-Saavn-Downloader#6]
will you try this jiosaavn api of mine?

https://github.com/cachecleanerjeet/jiosaavnapi

just use this server if you don't wanna create your server for testing

http://songapi.thetuhin.com/

**Comment by ParveenBhadooOfficial** [comment]
will, try

**Comment by cachecleanerjeet** [comment]
if you want any feature to impliment on this project just create an issue on it. **Thanks**
